name: Build

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16, 18, 20]
    uses: yoriiis/actions/.github/workflows/test-and-build.yml@main
    with:
      node-version: ${{ matrix.node-version }}
      os: ${{ matrix.os }}
      command-build: npm run build && npm run build:example
