name: Lint

on:
  workflow_dispatch:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: yoriiis/actions/.github/workflows/lint.yml@main
    with:
      eslint-config: 'config/.eslintrc.cjs'
      stylelint-config: 'config/stylelint.config.cjs'
