name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  deploy:
    uses: yoriiis/actions/.github/workflows/npm-publish.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
